#!/usr/bin/env sh
cd D:\Collaborateur\Medical\Code\iCasa\distribution\icasa-teaching-distribution\target\distrib-temp
exec java -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y -jar bin/felix.jar
